### ISSUE TITLE
Health endpoint shows binder status as UNKNOWN. 

### ISSUE THREAD

**Issue by sanketunche** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#114] opened 2019-10-08 12:17 UTC
I am using spring-cloud-stream-binder-kinesis library for reading data from Kinesis stream with build `1.1.0.RELEASE`. 

When I am calling `/health` endpoint the binder status is showing UNKNOWN.
I've enabled 
`management.health.binders.enabled`=`true`

Here is the output of `/health` endpoint
```

{
  "details": {
    "binders": {
      "details": {
        "kinesis": {
          "status": "UNKNOWN"
        }
      },
      "status": "UNKNOWN"
    },
    "camel": {
      "details": {
        "contextStatus": "Started",
        "version": "2.18.2"
      },
      "status": "UP"
    },
    "db": {
      "details": {
        "database": "MySQL",
        "hello": 1
      },
      "status": "UP"
    },
    "diskSpace": {
      "details": {
        "free": 8175505408,
        "threshold": 10485760,
        "total": 50259767296
      },
      "status": "UP"
    },
    "jms": {
      "details": {
        "provider": "ActiveMQ"
      },
      "status": "UP"
    },
    "redis": {
      "details": {
        "version": "5.0.4"
      },
      "status": "UP"
    }
  },
  "status": "UP"
}
```

**Comment by artembilan** [comment] 2019-10-14 20:30
Duplicate of #105

**Closed by artembilan** 2019-10-14 20:30 UTC
