### ISSUE TITLE
Long delays around 30 seconds for the Kinesis consumer running on Spring cloud stream

### ISSUE THREAD

**Issue by gongmingqm10** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#133] opened 2020-04-21 08:29 UTC
## My Environment

Kinesis Version: 1.2.1.RELEASE
Spring Cloud Version: 2.1.0.RELEASE
Spring Framework Version: 5.1.4.RELEASE
JRE: Java 8

build.gradle
```
buildscript {
    ext {
        springBootVersion = '2.1.2.RELEASE'
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:2.7"
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'org.sonarqube'
apply plugin: 'jacoco'

ext {
    springCloudVersion = 'Hoxton.SR3'
}

dependencies {
    compile group: 'net.logstash.logback', name: 'logstash-logback-encoder', version: '4.11'
    compile group: 'io.netty', name:'netty-all', version: '4.1.21.Final'
    compile group: 'org.apache.commons', name: 'commons-lang3', version: '3.7'
    compile group: 'com.google.code.gson', name: 'gson',version: '2.8.0'
    implementation 'org.springframework.boot:spring-boot-starter-aop'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.kafka:spring-kafka:2.2.2.RELEASE'
    implementation 'org.springframework.cloud:spring-cloud-starter-vault-config:2.1.0.RELEASE'
    implementation 'org.springframework.cloud:spring-cloud-starter-config:2.1.0.RELEASE'
    implementation "org.springframework.cloud:spring-cloud-stream-binder-kinesis:1.2.1.RELEASE"
}
```
My application.properties
```
spring.kafka.bootstrap-servers=xxxxxxx
spring.kafka.auto-commit.enable=false
spring.kafka.consumer.group-id=xx-groupqa-local

cloud.aws.region.static=ap-southeast-1
cloud.aws.stack.auto=false

spring.cloud.stream.bindings.input.destination=aws-iot-kinesis2
spring.cloud.stream.bindings.input.group=iot-kinesis-local
spring.cloud.stream.bindings.input.content-type=application/json

```

KinesisConsumer.java
```
@Slf4j
@Component
@EnableBinding(Sink.class)
public class IoTKinesisConsumer {

    @StreamListener(Sink.INPUT)
    public void consumer(String message) {
        log.error("!!!!!!!!!!!!!!!!Received Kinesis message: " + message);
    }
}

```

## What I observed

The original message was uploaded from the below flow:

**IoT Devices -> AWS IoT Core -> Kinesis Data Streams -> Spring Cloud Stream Kinesis Service**

And when I simulated the IoT message publish by MQTT client running in my local Mac. It will publish the topic every 10 millionseconds like the below code:

```
        for (int index = 0; index < 50000; index++) {
            Position position = new Position(index, "position-" + index, simpleDateFormat.format(new Date()));
            Thread.sleep(10);
            client.publish("scooters/" + clientId + "/gps", mapper.writeValueAsString(position));
        }
```

The thing is when I run the two applications in my local mac. One is for the MQTT client publish, and another is using the Spring cloud streams Kinesis to consume the message published to the Kinesis Data Streams.

But unluckily, I observed around 33 seconds relay when I run this application. It's super slow and cannot be used. You can see the message printed in the below:

**I can observe the continuous message consumer delayed for 33 seconds.** 

![Screen Shot 2020-04-21 at 4 17 59 PM](https://user-images.githubusercontent.com/4431171/79842718-c8583a80-83eb-11ea-9ceb-8975123130f2.png)
![image](https://user-images.githubusercontent.com/4431171/79842769-df972800-83eb-11ea-9de3-db668be38b03.png)

### 1. Upgrading to the latest Spring Cloud Kinesis 

I tried upgrading the Spring Cloud Kinesis to the latest 2.0.1.RELEASE version. But no luck. I still get almost the same message delayed.

### 2. Maybe it was the AWS Kinesis's fault?

Let's try it with the original AWS KCL to consume the same message.

```
dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile group: 'com.amazonaws', name: 'aws-iot-device-sdk-java', version: '1.3.6'
    compile group: 'com.amazonaws', name: 'amazon-kinesis-client', version: '1.13.3'
    compile group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: '2.8.11'
    compile group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.8.11'
    compile group: 'com.fasterxml.jackson.dataformat', name: 'jackson-dataformat-cbor', version: '2.8.11'
    compile group: 'commons-codec', name: 'commons-codec', version: '1.14'
}
```
Inspired by the demo: https://github.com/crossroad0201/aws-kcl-example/tree/master/java-example/

**Guess what, the message consumed in the KCL demo is quite real-time. Only 1-2 seconds delay.** 

## My Question

I hope I am not the only one who had this issue. Please correct me if it was caused my the wrong application.properties configuration.

Thanks,
Ming

**Comment by artembilan** [comment] 2020-04-21 14:23
> I tried upgrading the Spring Cloud Kinesis to the latest 2.0.1.RELEASE version

With that version there is already a `kplKclEnabled` option to switch the Kinesis binder to the KCL mode.
Please, try with that and let us know how it works.

Also try to play with `recordsLimit` and `idleBetweenPolls`. Because it looks like you still get some bunch of messages in the same millisecond, but then you get some sleep at about 30 seconds.

**Comment by artembilan** [comment] 2020-04-21 15:43
Would be better if you share your logs as text, so I could copy/paste it for context.
But OK. You see you have a delay between `Checkpointing shard ...` and `Current stream shard assignements ...` .

It looks like there are some problems with your DymanoDB: it doesn't let us to perform an update fast.
In your pure KCL sample there is no at runtime checkpointing. You do that only on shutdown.

You probably can emulate something similar with a `checkpointMode = manual`.

Or we can think about new `shutdown` mode...

**Comment by gongmingqm10** [comment] 2020-04-21 16:23
> Your uses Kinesis & DynamoDB SDK v2, so might be some difference at runtime behavior.

So what's the suggested version I should use？ You mean I should explicitly declare use the DynamoDB V1 in the build.gradle?

So what expectation in my side. I want to start using the v2.0.1 library, and want to control the consumer delay in 1 sec.

**Comment by artembilan** [comment] 2020-04-21 16:33
Then you can't use this library because it doesn't support AWS SDK v2 yet. See issues GH around.

The expectation that you troubleshoot why you have that delay during checkpointing.

No one complained on the matter, so, I'm not sure how to help.
The `kplKclEnabled=true` fully does whatever you show in your sample with `checkpointMode=batch` by default. 
Need to debug on your side how that `checkpointer.checkpoint();` is different in the `KclMessageDrivenChannelAdapter` and your own `ExampleRecordProcessor`.

**Comment by gongmingqm10** [comment] 2020-04-21 16:53
ok, understand what you mean. So for now, I will roll back to use the KCL library and manually integrate it to my project to keep things moving. But if I found anything can explain the things we encountered in this thread, I will share more message in this topic. Thanks for the explain and help.

**Comment by gongmingqm10** [comment] 2020-04-22 00:36
The log file attached as below with: `logging.level.org.springframework.integration.aws=DEBUG`
[debug.log](https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/files/4513196/debug.log)

**Comment by artembilan** [comment] 2020-04-22 20:12
Well, it doesn't look like your final solution reflects what you show in a simple sample.
What does Kafka do in this application?
Does it really work the same (bad) way when you have only Kinesis?

This is my first observation:
```

{"tags":["xxx"],"project":"yyy","timestamp":"2020-04-22T00:39:44,826+0800","log_level":"INFO","thread":"SimpleAsyncTaskExecutor-3","message":"Initializing shard shardId-000000000000 with 49606257641189450910225638961269841850629493682492932098","stack_trace":"","session_id":"","module_name":""}
{"tags":["xxx"],"project":"yyy","timestamp":"2020-04-22T00:39:45,937+0800","log_level":"INFO","thread":"SimpleAsyncTaskExecutor-3","message":"Initializing record processor for shard: shardId-000000000000","stack_trace":"","session_id":"","module_name":""}
{"tags":["xxx"],"project":"yyy","timestamp":"2020-04-22T00:39:57,994+0800","log_level":"DEBUG","thread":"SimpleAsyncTaskExecutor-4","message":"Processing 1038 records from shardId-000000000000","stack_trace":"","session_id":"","module_name":""}
{"tags":["xxx"],"project":"yyy","timestamp":"2020-04-22T00:39:58,001+0800","log_level":"ERROR","thread":"SimpleAsyncTaskExecutor-4","message":"!!!!!!!!!!!!!!!!Received Kinesis message: {\"index\":15237,\"name\":\"position-15237\",\"clientDate\":\"00:31:58.696\"}","stack_trace":"","session_id":"","module_name":""}
See that delay between `Initializing`  and `Processing` messages.
The code is here:
```
	private class RecordProcessor implements IRecordProcessor {

		@Override
		public void initialize(String shardId) {
			this.shardId = shardId;
			if (logger.isInfoEnabled()) {
				logger.info("Initializing record processor for shard: " + this.shardId);
			}
		}

		@Override
		public void processRecords(List<Record> records, IRecordProcessorCheckpointer checkpointer) {
			if (logger.isDebugEnabled()) {
				logger.debug("Processing " + records.size() + " records from " + this.shardId);
			}
```

This is already kinda out of this project  scope: we fully can't control how KCL calls these its method and why there is such a delay in between even if we haven't reached end-user code yet.

Then I see this after the mentioned batch:
```
{"tags":["xxx"],"project":"yyy","timestamp":"2020-04-22T00:39:58,128+0800","log_level":"ERROR","thread":"SimpleAsyncTaskExecutor-4","message":"!!!!!!!!!!!!!!!!Received Kinesis message: {\"index\":16275,\"name\":\"position-16275\",\"clientDate\":\"00:32:10.178\"}","stack_trace":"","session_id":"","module_name":""}
{"tags":["xxx"],"project":"yyy","timestamp":"2020-04-22T00:39:58,128+0800","log_level":"INFO","thread":"SimpleAsyncTaskExecutor-4","message":"Checkpointing shard shardId-000000000000","stack_trace":"","session_id":"","module_name":""}
{"tags":["xxx"],"project":"yyy","timestamp":"2020-04-22T00:40:02,322+0800","log_level":"DEBUG","thread":"SimpleAsyncTaskExecutor-5","message":"Processing 629 records from shardId-000000000000","stack_trace":"","session_id":"","module_name":""}
{"tags":["xxx"],"project":"yyy","timestamp":"2020-04-22T00:40:02,322+0800","log_level":"ERROR","thread":"SimpleAsyncTaskExecutor-5","message":"!!!!!!!!!!!!!!!!Received Kinesis message: {\"index\":16282,\"name\":\"position-16282\",\"clientDate\":\"00:32:10.258\"}","stack_trace":"","session_id":"","module_name":""}

So, checkpointing an offset and starting a new batch takes only `4 seconds`. Not too bad in comparison with your original concern.

The next one is like this:
```
{"tags":["xxx"],"project":"yyy","timestamp":"2020-04-22T00:40:02,377+0800","log_level":"ERROR","thread":"SimpleAsyncTaskExecutor-5","message":"!!!!!!!!!!!!!!!!Received Kinesis message: {\"index\":242,\"name\":\"position-242\",\"clientDate\":\"00:36:02.211\"}","stack_trace":"","session_id":"","module_name":""}
{"tags":["xxx"],"project":"yyy","timestamp":"2020-04-22T00:40:02,377+0800","log_level":"INFO","thread":"SimpleAsyncTaskExecutor-5","message":"Checkpointing shard shardId-000000000000","stack_trace":"","session_id":"","module_name":""}
{"tags":["xxx"],"project":"yyy","timestamp":"2020-04-22T00:40:16,015+0800","log_level":"INFO","thread":"SimpleAsyncTaskExecutor-1","message":"Current stream shard assignments: shardId-000000000000","stack_trace":"","session_id":"","module_name":""}
{"tags":["xxx"],"project":"yyy","timestamp":"2020-04-22T00:40:16,015+0800","log_level":"INFO","thread":"SimpleAsyncTaskExecutor-1","message":"Sleeping ...","stack_trace":"","session_id":"","module_name":""}
{"tags":["xxx"],"project":"yyy","timestamp":"2020-04-22T00:40:35,596+0800","log_level":"DEBUG","thread":"SimpleAsyncTaskExecutor-6","message":"Processing 1884 records from shardId-000000000000","stack_trace":"","session_id":"","module_name":""}
{"tags":["xxx"],"project":"yyy","timestamp":"2020-04-22T00:40:35,596+0800","log_level":"ERROR","thread":"SimpleAsyncTaskExecutor-6","message":"!!!!!!!!!!!!!!!!Received Kinesis message: {\"index\":240,\"name\":\"position-240\",\"clientDate\":\"00:36:02.187\"}","stack_trace":"","session_id":"","module_name":""}
```

Already is not good since we see those 15 seconds for checkpointing and 20 in between sleep and the next poll.

Probably something like rebalance or resharding happens internally in KCL...
Fully doesn't look we can control something. Probably we need an AWS consultation with this KCL configuration.

Would you mind to share logs when you have it without KCL?

Thanks for understanding.
```

**Comment by markathomas** [comment] 2021-03-12 10:21
I am having this same issue with Kinesis, how can I help debug?  Every event takes 15 seconds to appear

**Comment by artembilan** [comment] 2021-03-12 14:59
Hi @markathomas !

Thank you for reaching us!

The best way would be to have a simple application which just does consumer from the Kinesis without any extra logic in it. 
Then you can share that project with us to see what is going on and also share logs how it looks from your perspective.

Would be great if you can reproduce it with Localstack, so it is easy to debug on our side.
Otherwise it's all up to AWS and what throughput quota you have for your account

**Comment by markathomas** [comment] 2021-03-13 00:55
Hi @artembilan and sorry for jumping the gun here.  Evidentally, the environment was not reading my variables correctly on my local machine so I was never even connected to Kinesis.  After resolving this all is well.

**Comment by artembilan** [comment] 2021-06-04 17:55
Closed as `Cannot reproduce` without reporter feedback until now.

**Closed by artembilan** 2021-06-04 17:55 UTC
