### ISSUE TITLE
Investigate the official Kinesis client library

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#53] opened 2018-06-11 14:37 UTC
Refer to: https://github.com/awslabs/amazon-kinesis-client

**Comment by artembilan** [comment] 2018-06-19 19:36
After some investigation and reading KCL source code, it looks like there is nothing interesting for us.
What they do is just leasing for the particular shard without any notion of the `consumer group`.
That's definitely not what we are interested in.

The recent fix with the `LockRegistry` usage (https://github.com/spring-projects/spring-integration-aws/issues/90) brings us very close to what we have with the native consumer group management in the Apache Kafka, and now Kinesis Binder is able to get an exclusive access to the particular shard in the consumer group.

The next steps would be to come up with the leader election and rebalance implementation, where such a functionality would be managed by the master and some `CandidateRegistry`.

Nothing to do from this ticket perspective though. 

Closing as `Won't Fix`.

**Closed by artembilan** 2018-06-19 19:36 UTC
Labels: ready, spike

**Comment by danpeterson-exp** [comment] 2018-11-06 21:30
Just a point of clarification, KCL does appear to support the concept of "consumer group" via specifying an appName, and this does work in a very similar manner to a Kafka consumer group.  We've only been using KCL for a couple of months now, so it's possible that this was added recently.  We've tested this behavior locally by running two copies of our KCL consumers under using different appNames, and they both receive a copy of the same data.  This is confirmed here:  https://stackoverflow.com/a/50198905.

**Comment by r1m** [comment] 2018-11-09 09:34
If I understand correctly KCL also [support rebalancing](https://docs.aws.amazon.com/streams/latest/dev/kinesis-record-processor-scaling.html) after a resharding/scaling.
Maybe I'm wrong but it can also help to solve https://github.com/spring-projects/spring-integration-aws/issues/99
Plus bonus point, we could use KPL [aggregation&batching](https://docs.aws.amazon.com/streams/latest/dev/kinesis-kpl-concepts.html) that may help for https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/issues/65 and will reduce cost (less insertion, high throuput)

**Comment by artembilan** [comment] 2018-11-09 19:44
Sounds promising!

Anyone here is willing to contribute back to Spring Integration AWS the KCL and KPL Channel Adapters implementations?

Thank you for all the info!

**Comment by r1m** [comment] 2018-11-20 10:44
@artembilan,

We might have some time to look into this but we may need some guidance.
Our planing is tight, bu we might start working on this by the end of this month

I quickly scanned AWS integration code and as I understand most of the checkpointing code might become useless as well as DynamoDBLock and lockRegistry.

Entry points are KinesisMessageDrivenChannelAdapter and KinesisMessageHandler.
Is there anything we should worry about ?
Do we open a new issue on integration side ?

**Comment by artembilan** [comment] 2018-11-20 19:51
@r1m ,

Thank you for the effort and willing to contribute! That's really appreciated.

My point is to introduce new components based on the KCL and KPL without touching existing even if we may deprecate them eventually.

The idea how to implement those new components indeed should be borrowed from the mentioned `KinesisMessageDrivenChannelAdapter` and `KinesisMessageHandler`, but that's all. Nothing has to be broker in the project.

The  DynamoDB components can be used in many other use-cases, not only Kinesis. The goal of the Spring Integration AWS project is to bring well-know EIP implementations into the AWS environment, so we implement components there on demand, e.g. SQS and SNS, S3 and so on. 
Please, don't treat that project that it is only for Kinesis.

Hope that clears some concerns a bit.

Thank you again and looking forward for contribution!
