### ISSUE TITLE
Version 4.0.0 breaks compatibility with Spring Boot 2.x

### ISSUE THREAD

**Issue by olbat** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#206] opened 2023-09-06 15:28 UTC
The version 4.0.0 of the library is using [features from spring-integration 6.x](https://github.com/spring-projects/spring-integration/commit/bd207ff42a7bc88b3d4797d97126f47fc4002b84) that is only compatible with Spring Boot 3.x and therefore it breaks compatibility with previous versions of Spring Boot.

This might be an expected change, however:
- I could not find it documented anywhere, [the latest release notes](https://spring.io/blog/2023/03/27/spring-integration-for-aws-3-0-0-m2-and-spring-cloud-stream-kinesis-binder-4) mentioned an update to Spring Cloud 3.0.0, which iiuc is compatible with Spring Boot 2.x
- the [pom.xml file](https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/blob/main/pom.xml#L21) still references a dependency on spring-integration 3.x, even though the library uses features from version 6.x

That makes me wonder: _is that an expected change?_

If not, would it be possible to add a few extra checks in the code to make it possible to disable features that are only available in _spring-integration 6.x_ and make it possible to use this version of the binder with Spring Boot 2.x?

Thanks in advance 👍

**Comment by olbat** [comment] 2023-09-07 06:48
Alright, I understand, thank you for your support 👍 

That being said, I guess that the two points I mentioned in my message could possibly be improved (to avoid others wasting time trying to make the component work on Spring Boot 2.x).

**Comment by artembilan** [comment] 2023-09-08 21:23
The Spring Integration AWS is separate project from original Spring Integration:

https://github.com/spring-projects/spring-integration

https://github.com/spring-projects/spring-integration-aws

That's because the second one is based on Spring Cloud AWS, which, in turn, is based on Spring Cloud. And this one comes with some dependencies from Spring Integration.
Therefore separate projects with their own versions and release cycles.

If you think that only the mentioned observation support is broken, you can try with an explicit version for Spring Integration (`6.0.7` in particular) in your Spring Boot 2.x project: https://docs.spring.io/spring-boot/docs/2.7.15/maven-plugin/reference/htmlsingle/#using.parent-pom:

```
<properties>
    <spring-integration.version>6.0.7</spring-integration.version>
</properties>
```

But I still doubt that Spring Cloud `4.0.x` is compatible with Spring Boot `2.x`...

**Comment by artembilan** [comment] 2023-09-20 18:39
Closed as `Works as Designed`.
In other words: we don't claim compatibility with Spring Boot `2.x` and won't try because too much breaking changes, plus just to Java 17.

**Closed by artembilan** 2023-09-20 18:39 UTC
