### ISSUE TITLE
Erros when converting payload object to string at 1.0.0.M1 in a custom process

### ISSUE THREAD

**Issue by komushi** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#42] opened 2018-03-06 01:30 UTC
**The source app command:**
```
java -jar target/s3-source-rabbit-2.0.0.BUILD-SNAPSHOT.jar --s3.remoteDir=s3exp --file.consumer.mode=lines --spring.cloud.stream.bindings.output.producer.partitionKeyExpression=1  --spring.cloud.stream.bindings.output.destination=s3_lines --spring.cloud.stream.bindings.output.contentType=text/plain --server.port=8000 --spring.cloud.stream.defaultBinder=kinesis --cloud.aws.region.static=ap-northeast-1
```

**The processor app command:**
```
java -jar target/scs-processor-geocoding-reverse-2.0.0.BUILD-SNAPSHOT.jar --spring.cloud.stream.bindings.input.contentType=text/plain --spring.cloud.stream.bindings.input.destination=s3_lines --spring.cloud.stream.bindings.input.group=geocoding --spring.cloud.stream.bindings.output.destination=geojson --spring.cloud.stream.bindings.output.contentType=application/json --spring.cloud.stream.bindings.output.producer.partitionKeyExpression=1 --logging.level.info.cloudnative=TRACE --server.port=8020 --spring.cloud.stream.defaultBinder=kinesis --cloud.aws.region.static=ap-northeast-1
```

**The processor code:**
```
    @Transformer(inputChannel = Processor.INPUT, outputChannel = Processor.OUTPUT)
    public Tuple transform(Message<?> message) {
        if (logger.isTraceEnabled()) {
            logger.trace(String.format("Handling message: %s", message));
        }

        Object payloadObj = message.getPayload();
        String payload = null;

        if (payloadObj instanceof String) {
            logger.trace(String.format("payloadObj is String"));
            payload = payloadObj.toString();
        } else {
            logger.trace(String.format("payloadObj is byte[]"));
            byte[] bytes = (byte[])payloadObj;
            
            try {
                // Neither of the two below works with 1.0.0.M1 but both work with rabbit binder.
                // payload = new String(bytes);
                payload = new String(bytes, "UTF-8");    
            }
            catch (Exception ex) {
                throw new MessageTransformationException("payloadObj transform failed");
            }
            
        }

        if (logger.isTraceEnabled()) {
            logger.trace(String.format("payload: %s", payload));
        }
...
```

**The expected result:**
```
2018-03-06 10:09:36.251  INFO 23006 --- [           main] i.c.s.p.g.r.ScsProcessorGeocodingReverse : Started ScsProcessorGeocodingReverse in 8.327 seconds (JVM running for 8.955)
2018-03-06 10:10:45.193 TRACE 23006 --- [nes.geocoding-1] .c.s.p.g.r.ReverseGeocodingConfiguration : Handling message: GenericMessage [payload=byte[190], headers={amqp_receivedDeliveryMode=PERSISTENT, sequenceNumber=1, amqp_receivedExchange=s3_lines, amqp_deliveryTag=1, file_name=one_line.csv, sequenceSize=0, deliveryAttempt=1, amqp_consumerQueue=s3_lines.geocoding, amqp_redelivered=false, file_originalFile=/var/folders/yr/7rnnqb4n1r77yxl6_0w206dsv0z2pp/T/s3-source/one_line.csv, file_relativePath=one_line.csv, amqp_receivedRoutingKey=s3_lines, correlationId=4e1ed5ea-073a-557a-7115-177c8a26a472, id=f36002da-7f6a-b23d-158b-2ebfd1bf080f, amqp_consumerTag=amq.ctag-CGyO5T26_ufgRVtb-mNB-g, contentType=text/plain, timestamp=1520298645186}]
2018-03-06 10:10:45.193 TRACE 23006 --- [nes.geocoding-1] .c.s.p.g.r.ReverseGeocodingConfiguration : payloadObj is byte[]
2018-03-06 10:10:45.194 TRACE 23006 --- [nes.geocoding-1] .c.s.p.g.r.ReverseGeocodingConfiguration : payload: 468244D1361B8A3EB8D206CC394BC9E9,BB899DFEA9CC964B50C540A1D685CCFB,2017-01-01 00:00:00,2017-01-01 00:04:00,240,1.71,139.716268,35.587043,139.711699,35.677283,CSH,6.50,0.50,0.50,0.00,0.00,7.50
```

**The error result:**
```
2018-03-06 10:13:24.677 TRACE 23054 --- [esis-consumer-1] .c.s.p.g.r.ReverseGeocodingConfiguration : Handling message: GenericMessage [payload=byte[180], headers={sequenceNumber=156, aws_shard=shardId-000000000000, sequenceSize=0, correlationId=baebf4d0-b7fa-5b08-e995-04e154e8b557, id=722b5069-a426-ce8f-4bde-2b43ff1a8d94, contentType=text/plain, aws_receivedStream=s3_lines, aws_receivedPartitionKey=partitionKey-0, aws_receivedSequenceNumber=49582317471515345120147026495478335654969437462313566210, timestamp=1520298804673}]
2018-03-06 10:13:24.677 TRACE 23054 --- [esis-consumer-1] .c.s.p.g.r.ReverseGeocodingConfiguration : payloadObj is byte[]
2018-03-06 10:13:24.677 TRACE 23054 --- [esis-consumer-1] .c.s.p.g.r.ReverseGeocodingConfiguration : payload: %K,�s�RX��_��m������5�����O�>�r51���?9��,���e�Ѫ�>��[C���.���ͫ��J��E)�C=6!U�$0+�
```

When using earlier version of 1.0.0.BUILD-SNAPSHOT(I cannot tell the exact date now) or the rabbit binder I can get the expected result.

**Comment by artembilan** [comment] 2018-03-06 02:54
I have just pushed a commit into the integration test-case to confirm that it works as expected: https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/commit/69ff2f3af74850e3872ab7f8ca3c81abdfb89776

Try with the latest `BUILD-SNAPSHOT`, please. 
Otherwise would be great if you can come up with stand-along as simple as possible Spring Boot application to let us to play on our side.

It's really hard to align Rabbit and Kinesis because the last one doesn't support `headers` , so we have to *embed* them into body when we send from the source and extract when receive in the processor/sink.

Thanks for understanding, but I really can't reproduce.

**Comment by komushi** [comment] 2018-03-06 04:13
Thanks a lot for the prompt response.

The issue might be with the output of the source app. 
The stream definition should look like below:
aws-s3-source | my-transform-processor

I have not tested other source apps.

**Comment by komushi** [comment] 2018-03-06 04:16
I understand rabbit works differently with kinesis but this same stream/settings used to be working in mid Feb but there is no such early versions in the repo any more.

Is it possible for you to test with source | processor?

**Comment by komushi** [comment] 2018-03-06 04:46
Just replaced the aws-s3-source with http-source. This time it works fine BUILD-SNAPSHOT. So it should be a aws-s3 issue not an issue with this binder. Sorry for the confusion.

**Comment by artembilan** [comment] 2018-03-06 15:02
Hm. That's still doesn't answer the question what is the problem and doesn't help you to go ahead with your solution.

Sounds good that you were able to narrow down the scope to the `aws-s3-source` project. So, maybe you can come up with some simple test-case around only that app and to determine what is wrong?

And confirm, please, that the same app works well with the current Rabbit Binder. And also that it doesn't work with Kinesis M1 and the latest BUILD-SNAPSHOT.

Let's don't close the issue issue since it really sounds like related to Kinesis Binder. Although I still don't understand what is missed...

**Comment by artembilan** [comment] 2018-03-06 15:08
What I see for the mode `lines` the `aws-s3-source`  populates this header:
```
flowBuilder.enrichHeaders(Collections.<String, Object>singletonMap(MessageHeaders.CONTENT_TYPE, "text/plain"))
```
But at the same time the binder does this in the `SendingHandler` because it is `embedfedHeaders`-restricted:
```
if (this.embedHeaders) {
	Object contentType = transformed.get(MessageHeaders.CONTENT_TYPE);
	// transform content type headers to String, so that they can be properly
	// embedded in JSON
	if (contentType != null) {
			transformed.put(MessageHeaders.CONTENT_TYPE, contentType.toString());
	}
```
So, sounds like the content-type is transferred properly. At least that looks like by the code...

Investigating... Although I won't reject any help on your side.

Thanks

**Comment by komushi** [comment] 2018-03-15 23:49
> And confirm, please, that the same app works well with the current Rabbit Binder. And also that it doesn't work with Kinesis M1 and the latest BUILD-SNAPSHOT.

It is correct. It does not work with the Kinesis M1 or the latest BUILD-SNAPSHOT. However Rabbit binder works.

**Comment by komushi** [comment] 2018-03-15 23:51
Let me re-create a stream like aws-s3-source | log-sink to simplify the use case. I will try both  Kinesis M1 and the latest BUILD-SNAPSHOT. The RabbitMQ binder will also be included.

**Comment by artembilan** [comment] 2018-03-15 23:57
Thanks. May we just have it without Rabbit Binder? I don't see reason to include it into the testing application if we really can reproduce with as simple as possible environment.

**Comment by artembilan** [comment] 2018-03-21 13:47
As I said before: consider to use the latest `BUILD-SNAPSHOT` for Kinesis Binder. The `aws-s3` is based on the latest SI AWS 2.0 BUILD-SNAPSHOT, so Kinesis Binder should be of the latest version as well.

And I guess that was an original reason of your issue.

Confirm, please, and let's close this ticket!

**Comment by komushi** [comment] 2018-04-11 05:51
I am not able to re-produce this error any more.

**Comment by artembilan** [comment] 2018-04-11 13:10
Thank you for the confirmation, @komushi !

Closing as "Works as Designed" according your latest feedback

**Closed by artembilan** 2018-04-11 13:10 UTC
Labels: help wanted
