### ISSUE TITLE
Unable to parse payload as JSON string due to Kinesis appending unknown chars

### ISSUE THREAD

**Issue by turboT4** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#113] opened 2019-10-06 15:29 UTC
Morning,

Recently I've been trying to local test the Kinesis connector and so far the results are no good with the latest build `1.2.1.RELEASE`.

I've been throwing several events at the same time and it fails to parse, at times, the payload into a valid JSON string as random IDs starting with the `$` symbol and chars are appended into the string, together with unknown chars at the beginning, middle and end of the event.

`a.i.k.KinesisMessageDrivenChannelAdapter : Got an exception during sending a 'GenericMessage (...)`

When trying to parse the incoming payload into Java, the following is thrown.

`Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('�' (code 65533 / 0xfffd))`

Also a thing to note, messages are produced by another service which happens to use the official Kinesis library, it isn't a Spring Cloud Streams producer. Could it be associated to the producer side instead?

However, I was wondering if this is something the consumer could clean up?

Again, this is something that happens ocassionally and I don't really know the workaround it if Kinesis is modifying the original bytes, as I've seen a similar issue here and supposedly a fix was release for it last year.

**Comment by artembilan** [comment] 2019-10-14 19:05
I think the problem is really wit incompatibility of the producer and consumer.
The Kinesis binder uses  `HeaderMode.embeddedHeaders` by default and as far as I know all other Kinesis clients do nothing with headers transferring because there is just no such a `headers` abstraction in the AWS Kinesis.
To align your producer and this consumer you should consider to turn that mode off: https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.0.M4/reference/html/spring-cloud-stream.html#_consumer_properties

> headerMode

>    When set to none, disables header parsing on input. Effective only for messaging middleware that does not support message headers natively and requires header embedding. This option is useful when consuming data from non-Spring Cloud Stream applications when native headers are not supported. When set to headers, it uses the middleware’s native header mechanism. When set to embeddedHeaders, it embeds headers into the message payload.

>    Default: depends on the binder implementation.

**Comment by artembilan** [comment] 2019-10-22 19:07
Closing due to inactivity.

**Closed by artembilan** 2019-10-22 19:07 UTC
Labels: question
